name: Deploy Space Pizza

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: npm ci

    - name: Build the project (if needed)
      run: npm run build

    - name: Set API keys
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        IPSTACK_API_KEY: ${{ secrets.IPSTACK_API_KEY }}
      run:
        echo 'done'